---
services: 
  - docker

jobs:
  include:
    - stage: Deploy Back
      script:
        - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        - docker-compose build
        - docker push seg78/api_timemanage
...
