export const SET_USERNAME = "SET_USERNAME";
export const SET_USER_EMAIL = "SET_USER_EMAIL";
export const SET_USER_ID = "SET_USER_ID";
export const SET_USER_ROLE = "SET_USER_ROLE";
export const SET_USER_FIRSTNAME = "SET_USER_FIRSTNAME";
export const SET_USER_LASTNAME = "SET_USER_LASTNAME";

export const SET_IS_CONNECTED = "SET_IS_CONNECTED";
